# Prometheus datasource for Grafana
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    org_id: 1
    url: http://172.17.0.1:9090
    is_default: true
    version: 1
    editable: false
