CREATE DATABASE requests;
USE requests;
CREATE TABLE requests(id int NOT NULL AUTO_INCREMENT,
uri varchar(255) NOT NULL,
body varchar(255),
date_created DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
PRIMARY KEY (id));
